version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    cpus: "0.5"
    mem_limit: "0.5g"
    ports:
      - "27017:27017"
    networks:
      - local_shared_network
  redis:
    image: redis
    container_name: redis
    cpus: "0.5"
    mem_limit: "0.5g"
    ports:
      - "6379:6379"
    networks:
      - local_shared_network
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    cpus: "0.5"
    mem_limit: "0.5g"
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: "local-database"
      MARIADB_USER: local
      MARIADB_PASSWORD: "QWER1qaz@#$"
      MARIADB_ROOT_PASSWORD: "QWER1qaz@#$R"
    networks:
      - local_shared_network
  postgres:
    image: postgres:15.5-alpine
    container_name: postgres
    restart: always
    cpus: "0.5"
    mem_limit: "0.5g"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: "local-database"
      POSTGRES_USER: local
      POSTGRES_PASSWORD: "QWER1qaz@#$"
      POSTGRES_ROOT_PASSWORD: "QWER1qaz@#$R"
    networks:
      - local_shared_network
networks:
  local_shared_network:
    external: false
